### PR TITLE
Fix Build InMemory StateStore Actor

### PR DESCRIPTION
**Pull request by hamzajg**
Fix  Build InMemory StateStore Actor

### CODE REVIEW

**Review by tjaskula — APPROVED** [review]
Nice

**Comment by tjaskula** [comment]
Do you have rights to restart CI for checks? I can do that

**Comment by VaughnVernon** [comment]
Is this question to Hamza?

**Comment by tjaskula** [comment]
@VaughnVernon Yes, indeed but I'll do it myself. It's just in a case he needs to do it again

**Comment by tjaskula** [comment]
@hamzajg @VaughnVernon Everything has passed. I can merge if this is finished

**Pull request merged**
